# Generated by Django 3.2.5 on 2023-02-16 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dispensary', '0001_initial'),
        ('files', '0001_initial'),
        ('users', '0002_auto_20230216_1233'),
        ('assesment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formassesment',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_assesments', to='dispensary.order'),
        ),
        migrations.AddField(
            model_name='formassesment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_assesments', to='users.patient'),
        ),
        migrations.AddField(
            model_name='avalability',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avalabilities', to='users.doctor'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='assesment.appointment'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='files.file'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='users.patient'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='availability',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='appointment', to='assesment.avalability'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='dispensary.order'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='users.patient'),
        ),
        migrations.AddField(
            model_name='answer',
            name='form_assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='assesment.formassesment'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='assesment.question'),
        ),
    ]
