# Generated by Django 3.2.5 on 2023-02-02 03:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_doctor_patient_pharmacyuser'),
        ('files', '0004_auto_20210701_1809'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='files.file')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='users.patient')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
